// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zwhmuyoxvokwhqiikhgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aG11eW94dm9rd2hxaWlraGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzE3MzcsImV4cCI6MjA3MTYwNzczN30.WVia0AxkhWaddOcxS1QTFhfSHByk2W9BtYsEvWZ59C8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);